# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.define "web" do |web|
        web.vm.box = "ubuntu/focal64"
        web.vm.network "forwarded_port", guest: 80, host: 8080
        web.vm.provider "virtualbox" do |vb|
            vb.cpus=2
            vb.memory="2048"
        end

        web.vm.provision "shell", inline: <<-SHELL
            apt update
            apt install -y apache2
        SHELL
    end

config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/focal64"
    web2.vm.network "forwarded_port", guest: 80, host: 8081
    web2.vm.provider "virtualbox" do |vb|
        vb.cpus=2
        vb.memory="1024"
    end

    web2.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2
    SHELL
end

end
